# Compreensão do Dataset

## 1. Importação das bibliotecas

## 2. Carregamento do dataset

## 3. Dimensões do dataset

## 4. Identificação das colunas

## 5. Tipos dos dados

## 6. Significado das colunas

## 7. Identificação de jogador, partida e kills

## 8. Estrutura dos registros

1 - Importando Bibliotecas e Carregando DataFrame

In [2]:
import pandas as pd

PATH = "../data/raw/tb_lobby_stats_player.csv"
df = pd.read_csv(PATH)

In [32]:
df.head()

,idLobbyGame,idPlayer,idRoom,qtKill,qtAssist,qtDeath,qtHs,qtBombeDefuse,qtBombePlant,qtTk,...,qtFlashAssist,qtHitHeadshot,qtHitChest,qtHitStomach,qtHitLeftAtm,qtHitRightArm,qtHitLeftLeg,qtHitRightLeg,flWinner,dtCreatedAt
0,1,1,1,5,1,16,2,0,0,0.0,...,0.0,3.0,13.0,4.0,2.0,2.0,1.0,0.0,0,2022-01-21 19:45:44
1,2,1,2,24,3,18,6,0,4,0.0,...,0.0,7.0,26.0,14.0,2.0,1.0,1.0,3.0,1,2022-02-04 02:09:47
2,3,2,3,6,4,23,2,0,1,0.0,...,0.0,3.0,15.0,8.0,1.0,2.0,0.0,2.0,0,2021-09-18 18:07:43
3,3,391,27508,10,5,20,4,1,0,0.0,...,0.0,6.0,27.0,10.0,1.0,7.0,6.0,6.0,1,2021-09-18 18:07:43
4,4,2,4,8,4,26,6,0,2,0.0,...,2.0,8.0,19.0,12.0,2.0,3.0,2.0,5.0,0,2021-09-27 00:17:45

In [27]:
datas = pd.to_datetime(df["dtCreatedAt"])

print("Data inicial:", datas.min())
print("Data final:", datas.max())

Data inicial: 2021-09-14 13:06:52
Data final: 2022-02-11 13:27:48

### 2 - Valores nulos

## 1. Visão Geral do Dataset
* **Total de Linhas (Registros):** 184.152
* **Total de Colunas:** 38
* **Linhas Sem Nulos (100% Completas):** 183.447
* **Linhas com Pelo Menos 1 Nulo:** 705 

## 2. Mapeamento de Valores Ausentes por Coluna

Das 38 colunas do dataset, **24 colunas possuem dados 100% preenchidos** e **14 colunas contêm valores ausentes (`NaN`)**, divididas em dois blocos principais:

### 🔹 Bloco 1: Estatísticas de Acertos Anatômicos e Ações Especiais (705 Nulos)
Contêm **705 valores ausentes**:
* `qtSurvived`
* `qtTrade`
* `qtFlashAssist`
* `qtHitHeadshot`
* `qtHitChest`
* `qtHitStomach`
* `qtHitLeftArm`
* `qtHitRightArm`
* `qtHitLeftLeg`
* `qtHitRightLeg`

### 🔹 Bloco 2: Estatísticas Detalhadas de Dano e Movimentação (120 Nulos)
Contêm **120 valores ausentes**:
* `qtTk`
* `qtTkAssist`
* `qtHits`
* `qtLastAlive`


## 3. Relação e Estrutura Entre os Nulos (Aninhamento)

* **Aninhamento Total:** Os nulos do **Bloco 2 (120 linhas)** estão **100% contidos** dentro do **Bloco 1 (705 linhas)**.
* **Detalhamento dos Grupos:**
  * **585 linhas:** Têm registros básicos (`qtHits`, `qtTk`), mas falharam em registrar acertos corporais e suporte (`qtHitChest`, `qtSurvived`).
  * **120 linhas:** Apresentam falha total nos dois blocos de métricas ao mesmo tempo.
  * **0 linhas:** Têm nulos isolados fora dessas 705 partidas.


## 4. Causa Raiz Identificada

* **Origem:** Instabilidade/falha técnica no plugin de telemetria do servidor durante partidas específicas (`idLobbyGame`).
* **Evidência:** Jogadores que possuem eliminações registradas (`qtKill` > 0 e `qtHs` > 0) aparecem com acertos em membros corporais como `NaN`, confirmando que a ação ocorreu na partida, mas o log anatômico/avançado do servidor não foi gravado/enviado para a base.

In [13]:
df.isna().sum()

idLobbyGame         0
idPlayer            0
idRoom              0
qtKill              0
qtAssist            0
qtDeath             0
qtHs                0
qtBombeDefuse       0
qtBombePlant        0
qtTk              120
qtTkAssist        120
qt1Kill             0
qt2Kill             0
qt3Kill             0
qt4Kill             0
qt5Kill             0
qtPlusKill          0
qtFirstKill         0
vlDamage            0
qtHits            120
qtShots             0
qtLastAlive       120
qtClutchWon         0
qtRoundsPlayed      0
descMapName         0
vlLevel             0
qtSurvived        705
qtTrade           705
qtFlashAssist     705
qtHitHeadshot     705
qtHitChest        705
qtHitStomach      705
qtHitLeftAtm      705
qtHitRightArm     705
qtHitLeftLeg      705
qtHitRightLeg     705
flWinner            0
dtCreatedAt         0
dtype: int64

In [ ]:
linhas_com_nulo = df.isna().any(axis=1).sum()

pct_linhas = (linhas_com_nulo / len(df)) * 100
print(f"Linhas com pelo menos um nulo: {linhas_com_nulo} ({pct_linhas:.2f}%)") # porcentagem de linhas nulas no dataset

Linhas com pelo menos um nulo: 705 (0.38%)

In [22]:
# analisando uma coluna especifica que tenha uma ou + linhas nulas 
# Colunas que você quer visualizar no resultado
colunas_desejadas = ['idLobbyGame', 'idPlayer','qtKill', 'qtTk', 'qtHits', 'qtLastAlive']

# Filtra onde 'qtTk' é nulo e exibe apenas as colunas desejadas
df[df['qtTk'].isna()][colunas_desejadas].head(5)

      idLobbyGame  idPlayer  qtKill  qtTk  qtHits  qtLastAlive
1725         1560        20      19   NaN     NaN          NaN
3099         2808        35      26   NaN     NaN          NaN
3642         3293        43      29   NaN     NaN          NaN
4896         4384        56      17   NaN     NaN          NaN
4897         4385        56      13   NaN     NaN          NaN

In [17]:
colunas = ['qtTk', 'qtTkAssist', 'qtHits', 'qtLastAlive']

# Quantidade de linhas onde TODAS as 4 colunas são nulas juntas
nulos_em_todas = df[colunas].isna().all(axis=1).sum()

# Quantidade de linhas onde PELO MENOS UMA é nula
nulos_em_qualquer = df[colunas].isna().any(axis=1).sum()

print(f"Linhas nulas em todas as 4 colunas ao mesmo tempo: {nulos_em_todas}")
print(f"Linhas nulas em qualquer uma das 4 colunas: {nulos_em_qualquer}")

if nulos_em_todas == 120 and nulos_em_qualquer == 120:
    print("\nSim! São exatamente as mesmas 120 linhas que têm nulos nessas colunas.")
else:
    print("\nNão, existem linhas diferentes onde ocorrem esses nulos.")

Linhas nulas em todas as 4 colunas ao mesmo tempo: 120
Linhas nulas em qualquer uma das 4 colunas: 120

Sim! São exatamente as mesmas 120 linhas que têm nulos nessas colunas.

In [ ]:
colunas = ['qtSurvived', 'qtTrade', 'qtFlashAssist', 'qtHitHeadshot', 'qtHitChest', 'qtHitStomach', 'qtHitLeftAtm', 'qtHitRightArm', 'qtHitLeftLeg', 'qtHitRightLeg']

# Quantidade de linhas onde TODAS as 10 colunas são nulas juntas
nulos_em_todas = df[colunas].isna().all(axis=1).sum()

# Quantidade de linhas onde PELO MENOS UMA é nula
nulos_em_qualquer = df[colunas].isna().any(axis=1).sum()

print(f"Linhas nulas em todas as 10 colunas ao mesmo tempo: {nulos_em_todas}")
print(f"Linhas nulas em qualquer uma das 10 colunas: {nulos_em_qualquer}")

if nulos_em_todas == 705 and nulos_em_qualquer == 705:
    print("\nSim! São exatamente as mesmas 705 linhas que têm nulos nessas colunas.")
else:
    print("\nNão, existem linhas diferentes onde ocorrem esses nulos.")

Linhas nulas em todas as 4 colunas ao mesmo tempo: 705
Linhas nulas em qualquer uma das 4 colunas: 705

Sim! São exatamente as mesmas 705 linhas que têm nulos nessas colunas.

In [24]:
# Verifica se as 120 linhas do grupo 1 também têm nulos no grupo 2
df[df['qtTk'].isna()]['qtSurvived'].isna().value_counts()

qtSurvived
True    120
Name: count, dtype: int64

In [29]:
# Exemplo: checar se há strings de texto representando nulos em colunas categóricas
mapas = df['descMapName'].value_counts(dropna=False)
print(mapas)
print(mapas.sum())

# Checar se existem valores negativos estranhos em contagens (ex: kills/hits)
df[['qtHits', 'qtSurvived', 'vlDamage']].min()

descMapName
de_mirage      58101
de_inferno     42073
de_dust2       23834
de_vertigo     19924
de_overpass    14088
de_nuke        14053
de_train        7846
de_ancient      4233
Name: count, dtype: int64
184152

qtHits        0.0
qtSurvived    0.0
vlDamage      0.0
dtype: float64

In [31]:
df.isna().sum()

idLobbyGame         0
idPlayer            0
idRoom              0
qtKill              0
qtAssist            0
qtDeath             0
qtHs                0
qtBombeDefuse       0
qtBombePlant        0
qtTk              120
qtTkAssist        120
qt1Kill             0
qt2Kill             0
qt3Kill             0
qt4Kill             0
qt5Kill             0
qtPlusKill          0
qtFirstKill         0
vlDamage            0
qtHits            120
qtShots             0
qtLastAlive       120
qtClutchWon         0
qtRoundsPlayed      0
descMapName         0
vlLevel             0
qtSurvived        705
qtTrade           705
qtFlashAssist     705
qtHitHeadshot     705
qtHitChest        705
qtHitStomach      705
qtHitLeftAtm      705
qtHitRightArm     705
qtHitLeftLeg      705
qtHitRightLeg     705
flWinner            0
dtCreatedAt         0
dtype: int64

In [ ]:
#Pq dos valores nulos 
df[df['qtSurvived'].isna()].head(3)

,idLobbyGame,idPlayer,idRoom,qtKill,qtAssist,qtDeath,qtHs,qtBombeDefuse,qtBombePlant,qtTk,...,qtFlashAssist,qtHitHeadshot,qtHitChest,qtHitStomach,qtHitLeftAtm,qtHitRightArm,qtHitLeftLeg,qtHitRightLeg,flWinner,dtCreatedAt
428,396,10,396,13,5,26,9,0,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2021-11-04 20:26:02
429,397,10,397,20,2,20,12,0,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2021-11-04 21:25:14
435,402,10,402,21,1,23,13,0,2,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2021-11-06 01:33:23

In [39]:
# Pega os IDs de partidas onde surgiram esses nulos
lobbies_com_nulo = df[df['qtSurvived'].isna()]['idLobbyGame'].unique()

# Verifica o total de registros dessas partidas na base inteira
df[df['idLobbyGame'].isin(lobbies_com_nulo)]['qtSurvived'].isna().value_counts()

qtSurvived
True    705
Name: count, dtype: int64

In [43]:
# Agrupa os nulos por data
df[df['qtSurvived'].isna()]['dtCreatedAt'].str[:10].value_counts()

dtCreatedAt
2021-10-27    48
2021-10-28    37
2021-10-29    30
2021-09-21    15
2022-01-19    13
              ..
2021-12-23     1
2021-12-31     1
2021-12-27     1
2021-12-21     1
2022-01-08     1
Name: count, Length: 111, dtype: int64

In [44]:
# Pega os IDs das partidas que contêm nulos
lobbies_com_nulo = df[df['qtSurvived'].isna()]['idLobbyGame'].unique()

# Verifica se nessas partidas TODOS os jogadores ficaram com nulos
df[df['idLobbyGame'].isin(lobbies_com_nulo)]['qtSurvived'].isna().value_counts()

qtSurvived
True    705
Name: count, dtype: int64

### 3 - Analisando as colunas

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 184152 entries, 0 to 184151
Data columns (total 38 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   idLobbyGame     184152 non-null  int64
 1   idPlayer        184152 non-null  int64
 2   idRoom          184152 non-null  int64
 3   qtKill          184152 non-null  int64
 4   qtAssist        184152 non-null  int64
 5   qtDeath         184152 non-null  int64
 6   qtHs            184152 non-null  int64
 7   qtBombeDefuse   184152 non-null  int64
 8   qtBombePlant    184152 non-null  int64
 9   qtTk            184032 non-null  float64
 10  qtTkAssist      184032 non-null  float64
 11  qt1Kill         184152 non-null  int64
 12  qt2Kill         184152 non-null  int64
 13  qt3Kill         184152 non-null  int64
 14  qt4Kill         184152 non-null  int64
 15  qt5Kill         184152 non-null  int64
 16  qtPlusKill      184152 non-null  int64
 17  qtFirstKill     184152 non-null  int64
 18  vlDamage        184152 non-null  int64
 19  qtHits          184032 non-null  float64
 20  qtShots         184152 non-null  int64
 21  qtLastAlive     184032 non-null  float64
 22  qtClutchWon     184152 non-null  int64
 23  qtRoundsPlayed  184152 non-null  int64
 24  descMapName     184152 non-null  str
 25  vlLevel         184152 non-null  int64
 26  qtSurvived      183447 non-null  float64
 27  qtTrade         183447 non-null  float64
 28  qtFlashAssist   183447 non-null  float64
 29  qtHitHeadshot   183447 non-null  float64
 30  qtHitChest      183447 non-null  float64
 31  qtHitStomach    183447 non-null  float64
 32  qtHitLeftAtm    183447 non-null  float64
 33  qtHitRightArm   183447 non-null  float64
 34  qtHitLeftLeg    183447 non-null  float64
 35  qtHitRightLeg   183447 non-null  float64
 36  flWinner        184152 non-null  int64
 37  dtCreatedAt     184152 non-null  str
dtypes: float64(14), int64(22), str(2)
memory usage: 53.4 MB

OBS -> as colunas colunas_float = [
    'qtHits', 'qtTk', 'qtTkAssist', 'qtLastAlive', 
    'qtSurvived', 'qtTrade', 'qtFlashAssist', 'qtHitHeadshot', 
    'qtHitChest', 'qtHitStomach', 'qtHitLeftAtm', 'qtHitRightArm', 
    'qtHitLeftLeg', 'qtHitRightLeg'
] podem sem transformadas para int, elas viraram float por causa dos nulos

In [56]:
df['qtHitLeftAtm'] #Deveria ser LeftArm

0         2.0
1         2.0
2         1.0
3         1.0
4         2.0
         ...
184147    1.0
184148    3.0
184149    1.0
184150    2.0
184151    5.0
Name: qtHitLeftAtm, Length: 184152, dtype: float64

In [47]:
df['qtHits']

0         25.0
1         54.0
2         31.0
3         63.0
4         51.0
          ...
184147    88.0
184148    63.0
184149    59.0
184150    65.0
184151    49.0
Name: qtHits, Length: 184152, dtype: float64

In [48]:
df['qtFlashAssist']

0         0.0
1         0.0
2         0.0
3         0.0
4         2.0
         ...
184147    0.0
184148    0.0
184149    0.0
184150    1.0
184151    0.0
Name: qtFlashAssist, Length: 184152, dtype: float64

In [51]:
df['qtLastAlive']

0         0.0
1         1.0
2         0.0
3         1.0
4         0.0
         ...
184147    1.0
184148    0.0
184149    0.0
184150    0.0
184151    0.0
Name: qtLastAlive, Length: 184152, dtype: float64

In [55]:
colunas_float = [
    'qtHits', 'qtTk', 'qtTkAssist', 'qtLastAlive', 
    'qtSurvived', 'qtTrade', 'qtFlashAssist', 'qtHitHeadshot', 
    'qtHitChest', 'qtHitStomach', 'qtHitLeftAtm', 'qtHitRightArm', 
    'qtHitLeftLeg', 'qtHitRightLeg'
]

# Verifica se a parte decimal de algum valor é diferente de zero (ignorando os NaN)
tem_quebrado = (df[colunas_float].dropna() % 1 != 0).any() # Remove os nulos temporariamente apenas para fazer a checagem

tem_quebrado

qtHits           False
qtTk             False
qtTkAssist       False
qtLastAlive      False
qtSurvived       False
qtTrade          False
qtFlashAssist    False
qtHitHeadshot    False
qtHitChest       False
qtHitStomach     False
qtHitLeftAtm     False
qtHitRightArm    False
qtHitLeftLeg     False
qtHitRightLeg    False
dtype: bool

In [ ]:
# O tipo de dtCreatedAt é str e não datetime
df["dtCreatedAt"]

0         2022-01-21 19:45:44
1         2022-02-04 02:09:47
2         2021-09-18 18:07:43
3         2021-09-18 18:07:43
4         2021-09-27 00:17:45
                 ...
184147    2021-11-27 16:47:57
184148    2021-12-10 01:08:48
184149    2022-01-09 21:01:10
184150    2022-01-14 17:42:37
184151    2022-01-18 02:39:01
Name: dtCreatedAt, Length: 184152, dtype: str

In [ ]:
"""Combinação jogador + partida não se repete, cada linha faz referência a um jogador"""
df.duplicated(subset=["idLobbyGame", "idPlayer"]).sum()

np.int64(0)